#!/bin/sh -x
out_dir="/Users/masako/Documents/SHINRA/2021-LinkJP/test_out/20210905/"
mkdir ${out_dir}l
mkdir ${out_dir}mint_e_02
mkdir ${out_dir}mint_e_02__slink_05
mkdir ${out_dir}mint_e_02__slink_05__winm_r
mkdir ${out_dir}mint_e_02_incl_1
mkdir ${out_dir}mint_e_02_winm_r
mkdir ${out_dir}mint_e_02__winm_r
mkdir ${out_dir}mint_e_02_attr_m
mkdir ${out_dir}mint_e_02_slink_05
mkdir ${out_dir}mint_e_02_slink_05_winm_r
mkdir ${out_dir}mint_p_02
mkdir ${out_dir}mint_p_02_incl_1
mkdir ${out_dir}mint_p_02_slink_05
mkdir ${out_dir}mint_p_02_slink_05_winm_r
mkdir ${out_dir}mint_p_02_winm_r
mkdir ${out_dir}mint_p_02_winm_r__slink_05
mkdir ${out_dir}mint_p_02_winm_r_slink_05
mkdir ${out_dir}slink_05
mkdir ${out_dir}slink_05__mint_e_02__winm_r
mkdir ${out_dir}slink_05__winm_r__mint_e_02
mkdir ${out_dir}slink_05_winm_r__mint_e_02
mkdir ${out_dir}slink_05_mint_e_02_winm_r
mkdir ${out_dir}tinm_e_02
mkdir ${out_dir}tinm_e_02__winm_r
mkdir ${out_dir}tinm_e_02_slink_05
mkdir ${out_dir}tinm_e_02_winm_r
mkdir ${out_dir}tinm_p_02
mkdir ${out_dir}tinm_p_02_incl_1
mkdir ${out_dir}winm_r
mkdir ${out_dir}winm_r__mint_e_02
mkdir ${out_dir}winm_r__slink_05__mint_e_02
mkdir ${out_dir}winm_r__slink_05_mint_e_02
mkdir ${out_dir}winm_r__mint_e_02__slink_05
mkdir ${out_dir}winm_u
mkdir ${out_dir}winm_u__slink_05__mint_e_02
mkdir ${out_dir}winm_u__slink_05_mint_e_02
mkdir ${out_dir}winm_u__mint_e_02__slink_05
mkdir ${out_dir}winm_u_slink_05__mint_e_02
mkdir ${out_dir}winm_u_slink_05_mint_e_02
mkdir ${out_dir}winm_u_mint_e_02_slink_05